apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.grocery.name }}
spec:
  replicas: {{ .Values.grocery.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.grocery.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.grocery.name }}
    spec:
      containers:
      - name: grocery
        image: "{{ .Values.grocery.image }}"
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"
        ports:
        - containerPort: {{ .Values.grocery.containerPort }}
        readinessProbe:
          initialDelaySeconds: {{ .Values.healthCheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthCheck.periodSeconds }}
          httpGet:
            path: {{ .Values.healthCheck.path }}
            port: {{ .Values.grocery.containerPort }}
        env:
        - name: INVENTORY_URL
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.config.name }}
              key: {{ .Values.config.inventory }}


---
apiVersion: v1
kind: Service
metadata:
 name: {{ .Values.grocery.serviceName }}
spec:
  selector:
    app: {{ .Values.grocery.name }}
  type: NodePort
  ports:
  - port: {{ .Values.grocery.servicePort }}
    targetPort: {{ .Values.grocery.containerPort }}
    nodePort: {{ .Values.grocery.nodePort }}
