apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-inventory
spec:
  replicas: 3
  selector:
    matchLabels:
      app: new-inventory

  template:
    metadata:
      labels:
        app: new-inventory
    spec:
      containers:
      - name: new-inventory
        image: sanixsandel/new_inventory:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
         - containerPort: 5002


---
apiVersion: v1
kind: Service
metadata:
 name: new-inventory-service
spec:
  type: NodePort
  selector:
    app: new-inventory
  ports:
  - port: 9003
    targetPort: 5002
    nodePort: 30004
